# Add configuration values here, as shown below.
#
pusher_app_id: "707123"
pusher_key: 241faefb5fe729e1068e
pusher_secret: 14571652eae6e1518ddf
pusher_cluster: us2
#stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
#stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
